import Head from "next/head";
import { useState } from "react";
import {
  Container,
  Box,
  Typography,
  TextField,
  ButtonGroup,
  Button,
  Select,
  MenuItem,
  CircularProgress,
} from "@mui/material";
import { GridColDef, DataGrid } from "@mui/x-data-grid";
import { TParticipant } from "@/types/data.type";
import {
  useGetParticipantsQuery,
  useAddParticipantMutation,
} from "@/redux/services/participants";

type TFormState = Omit<TParticipant, "id">;

export default function Home() {
  const [formData, setFormData] = useState<TFormState>({
    name: "",
    email: "",
    gender: "Male",
    phoneNumber: "",
    city: "",
  });

  const { data, isLoading } = useGetParticipantsQuery();

  const [addParticipant, { isLoading: isAddLoading }] =
    useAddParticipantMutation();

  const updateFormData = (newVales: Partial<TFormState>) =>
    setFormData((prev) => ({ ...prev, ...newVales }));

  const columns: GridColDef[] = [
    { field: "name", headerName: "Name", width: 200 },
    { field: "gender", headerName: "Gender", width: 150 },
    { field: "email", headerName: "Email", width: 250 },
    { field: "phoneNumber", headerName: "Phone Number", width: 150 },
    { field: "city", headerName: "City", width: 150 },
  ];

  const clearForm = () =>
    updateFormData({
      name: "",
      email: "",
      gender: "Male",
      phoneNumber: "",
      city: "",
    });

  const onSubmitHandler = () => {
    addParticipant(formData)
      .unwrap()
      .then(() => {
        clearForm();
      });
  };

  return (
    <>
      <Head>
        <title>Sample Data Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxWidth="xl"
        sx={{
          display: "flex",
          flexDirection: "row",
          alignItems: "flex-start",
          justifyContent: "center",
          height: "98vh",
          gap: 2,
        }}
      >
        <Box height="100%" width="100%" sx={{ maxWidth: "50%" }}>
          <Typography variant="h4" component="h1" gutterBottom paddingTop={5}>
            Participant Data Form
          </Typography>
          <Box>
            <form
              onSubmit={(e) => {
                e.preventDefault();
                onSubmitHandler();
              }}
            >
              <TextField
                label="Name"
                variant="outlined"
                fullWidth
                margin="normal"
                required
                value={formData.name}
                onChange={(e) => updateFormData({ name: e.target.value })}
              />
              <Box marginTop={1}>
                <Select
                  labelId="gender-select-label"
                  variant="outlined"
                  label="Gender"
                  fullWidth
                  value={formData.gender}
                  onChange={(e) => updateFormData({ gender: e.target.value })}
                >
                  <MenuItem value="Male">Male</MenuItem>
                  <MenuItem value="Female">Female</MenuItem>
                </Select>
              </Box>
              <TextField
                label="Email"
                type="email"
                variant="outlined"
                fullWidth
                margin="normal"
                required
                value={formData.email}
                onChange={(e) => updateFormData({ email: e.target.value })}
              />
              <TextField
                label="Phone Number"
                type="tel"
                variant="outlined"
                fullWidth
                margin="normal"
                onChange={(e) =>
                  updateFormData({ phoneNumber: e.target.value })
                }
                value={formData.phoneNumber}
                required
              />
              <TextField
                label="City"
                variant="outlined"
                fullWidth
                margin="normal"
                onChange={(e) => updateFormData({ city: e.target.value })}
                required
                value={formData.city}
              />
              <ButtonGroup
                sx={{
                  marginTop: 1,
                  display: "flex",
                  justifyContent: "flex-end",
                }}
              >
                <Button
                  type="submit"
                  variant="contained"
                  color="primary"
                  sx={{ marginRight: 1 }}
                  disabled={isAddLoading}
                >
                  Submit
                </Button>
                <Button
                  type="reset"
                  variant="outlined"
                  color="primary"
                  disabled={isAddLoading}
                >
                  Reset
                </Button>
              </ButtonGroup>
            </form>
          </Box>
        </Box>
        <Box
          height="100%"
          width="100%"
          sx={{ maxWidth: "50%", paddingTop: 13.6, maxHeight: "100%" }}
        >
          {isLoading ? (
            <Box
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                paddingTop: 15,
              }}
            >
              <CircularProgress />
            </Box>
          ) : (
            <DataGrid columns={columns} rows={data?.data || []} />
          )}
        </Box>
      </Container>
    </>
  );
}
